### ISSUE TITLE
Tax report[RU]: empty summary fields

### ISSUE THREAD

**Issue by esemi** [titov-vv/jal#14]
Делал всё по инструкции, курсы подгрузил, суммы всех операций посчитались корректно, но в колонках "Итого" всё по нулям на всех листах (комиссии/сделки/дивы)
![image](https://user-images.githubusercontent.com/4115497/105577773-afbaed80-5d8c-11eb-8ce1-a03a1705cb09.png)

**Comment by titov-vv** [comment]
Это особенность OpenOffice Calc - по умолчанию он не пересчитывает формулы при открытии файла.
Можно пересчитать по F9 или Ctrl-Shift-F9. Можно глобально изменить через настройки Tools -> Cell Contents -> AutoCalculate.
Добавилю как примечание в инструкцию.

**Comment by titov-vv** [comment]
Documentation was updated with 7519667
