### ISSUE TITLE
Tax report: missed one of trades (GLTR ticker)

### ISSUE THREAD

**Issue by esemi** [titov-vv/jal#15]
В налоговом отчёте потерялась одна из сделок. При этом в отчёте и в базе она есть 
![image](https://user-images.githubusercontent.com/4115497/105628861-8a8fb300-5e50-11eb-8a90-b8d18093c0b9.png)

Налоговый отчёт генерирую за 20 год, другие три сделки есть, а по данному тикеру пустота
![image](https://user-images.githubusercontent.com/4115497/105628899-c32f8c80-5e50-11eb-9cfc-7c0dce0cec10.png)

Отчёт обезличенный прилагаю
[titov-vv_jal_anon.xml.zip](https://github.com/titov-vv/jal/files/5862102/titov-vv_jal_anon.xml.zip)

**Comment by titov-vv** [comment]
Не воспроизводится, у меня все сделки в наличии.
Есть подозрение, что т.к. XML не содержал секции Security Info, то GLTR была по ошибке добавлена не с типом Stock или Fund, а каким-то другим (значение по умолчанию Money). Данная страница налогового отчёта формируется только для акций или фондов, поэтому если Asset оказался с другим типом, то он туда не попадёт (коссвенно это подтверждается тем что "при этом в отчёте ... она есть" - я так понимаю речь идёт о Reports/Deals).

![not_reproduced](https://user-images.githubusercontent.com/55182132/105638452-bed09700-5e83-11eb-8cfe-eaa79d631fa8.png)

**Comment by esemi** [comment]
ага, секунду, проверю
возможно человеческий фактор при кликах на импорте)
