### ISSUE TITLE
Tax report: Процент на остаток по счёту попал в комиссии

### ISSUE THREAD

**Issue by esemi** [titov-vv/jal#16]
Процент на остаток кеша на счёте IB зачислил на счёт в соответствующей валюте.
В отчёте по налогам эти начисления попали в комиссии и уменьшили их. Не уверен, что это корректно - эти поступления вроде бы нужно подавать с отдельным кодом дохода и платить с них налог.
Даже если можно их сальдировать с комиссиями за неактивность, логично было бы видеть эти поступления на отдельном листе.

Так выглядит в отчёте брокера
![image](https://user-images.githubusercontent.com/4115497/105629221-c6c41300-5e52-11eb-8bcf-418c8818cf05.png)

Вот так зачлось в налоговом отчёте
![image](https://user-images.githubusercontent.com/4115497/105629252-eeb37680-5e52-11eb-990e-a5b55428cf51.png)

**Comment by titov-vv** [comment]
Да, это вроде код 1011 должен быть. Выделю отдельным.
