### ISSUE TITLE
ERROR - Неверный формат файла резервной копии

### ISSUE THREAD

**Issue by mrumskiy** [titov-vv/jal#17]
Сделал резервную копию (Данные-> Бэкап..)
Пытаюсь восстановиться из резервной копии (Данные->Восстановление..)
Получаю ошибку "ERROR - Неверный формат файла резервной копии" 
Что делаю неверно? 

Использую данный механизм чтобы вернуть БД в исходное состояние, т.к. проводок много и удалять за весь период вручную совсем не вариант.

**Comment by titov-vv** [comment]
Думаю вы всё делаете верно, но подозреваю, что вы сделали бэкап, потом обновили версию программы (сделали pull с github'а) и после этого пробуете восстановить. Дело в том, что пока формат базы данных ещё иногда периодически меняется - *jal* при старте старую версию конвертирует в новую в таком случае. А вот как в этом случае лучше поступать с бэкапами я ещё не решил - в результате бэкап можно восстановить на той версии базы данных, на которой он был создан.

Соответвтвенно могу порекомендовать следующее:
A) Если нужно восстановить именно этот бэкап:
1. Взять ту версию *jal*, в которой он был создан (думаю можно просто по дате бэкапа посмотреть и взять соответствующий коммит, но если не получается - напишете, я скажу как узнать нужную версию базы данных)
2. Восстановить бэкап на этой версии.
3. Обновить версию *jal* и запустить её - при запуске должно появиться сообщение что версия базы данных будет обновлена - соглашайтесь.
4. Дальше всё как обычно

B) Если вам просто нужно хранить базу данных в каком-то состоянии (например, если вы создали нужные счета-валюты, а потом просто хотите импортировать отчёты) - то вы можете просто сохранять файл `jal.sqlite` из каталога программы. В этом файле находится вся информация и если в последующем вы его захотите использовать с новой версией, то база данных сконвертируется автоматически.

C) Если вам просто необходимо обнулить всё и "начать с чистого листа", то достаточно просто удалить файл `jal.sqlite`

**Comment by titov-vv** [comment]
Я поменял механизм бэкапа в 8a7f49f - теперь сохраняется весь sqlite-файл полностью внутри архива. Поэтому при будущих изменениях версия это не должно больше вызывать описанную выше проблему.
