### ISSUE TITLE
Tax Report[RU] exception for declaration file

### ISSUE THREAD

**Issue by jetfraer** [titov-vv/jal#20]
При попытке генерации файла "Декларация 2020" возникает exception
![image](https://user-images.githubusercontent.com/80484013/110842087-b90a0600-82b7-11eb-8c3f-d93d66792a28.png)
Поскольку ссылка на Country code, есть подозрение, что дело в тикере VALE, у которого не определяется страна (скриншот со вкладки "Дивиденды":
![image](https://user-images.githubusercontent.com/80484013/110842337-04241900-82b8-11eb-989b-d700a17fd3f0.png)
Если нужен полный отчет IBKR, могу выслать приватно.

**Comment by titov-vv** [comment]
Да, дело в стране - 'Country_br' значит, что Бразилия (я так понимаю BR это она) добавилась из отчёта IB.
Переименовать её в Бразилию можно в меню Data->Coutries - это поможет сделать правильное название в файле xls.
С декларацией всё чуть сложнее, в JAL не внесены все коды стран, используемые ЦБ РФ и налоговой. Бразилию завтра добавлю. Полный список как-нибудь позже (надо его сначала где-нибудь взять... руками из программы декларация немного лень вытаскивать все по одному)

**Comment by jetfraer** [comment]
Спасибо! Как правильно обновлять программу - заново сделать pip install?
Судя по Консультанту, СОИДН с Бразилией есть, это тоже добавите? Или можно где-то руками указать?

**Comment by titov-vv** [comment]
Хм... Я вот тут СОИДН смотрю - https://www.nalog.ru/rn77/about_fts/inttax/mpa/dn/ там Бразилии нет. Поэтому по умолчанию оставлю "нет".
Но это легко настраивается - там же, в меню Data->Country в правом столбце, где звёздочки, щёлкнуть мышкой - звёздочка либо появится, либо исчезнет. Потом сохранить.

Если ставили через `pip install` то обновляться думаю через него же лучше, но следующий релиз сегодня не сделаю - в планах есть ещё ряд изменений, поэтому где-то думаю в течение недельки-другой должен зарелизить.
Если ждать не хочется, то можно руками взять отсюда новый файл dlsg.py и заменить его у себя, после того, как я закрою эту issue.

(Я стараюсь релизы делать в каких-то более-менее стабильных точках между большим количеством изменений)
