### ISSUE TITLE
Declaration file uses transaction date not settlement date

### ISSUE THREAD

**Issue by jetfraer** [titov-vv/jal#21]
В генерируемой декларации для операций с ЦБ указывается дата продажи и курс на эту дату. При этом в Excel таблице рублевые расчеты ведутся по дате расчетов. Есть разные мнения, указывать ли в декларации T или T+2 (я считаю T+2 вернее), но по крайней мере Excel и декларация должны придерживаться одного подхода. Я бы предложил сделать в декларации T+, либо соответствующую настройку. 
![image](https://user-images.githubusercontent.com/80484013/111027705-f8913900-8402-11eb-9d04-9410081917f4.png)
![image](https://user-images.githubusercontent.com/80484013/111027731-2f674f00-8403-11eb-87c7-6f6df85f7002.png)

**Comment by titov-vv** [comment]
Да, думаю вы правы и это конечно же ошибка. В данном случае дата получения дохода (Т+2) 28.05.2020. А остальное уже расходная часть. 
Я просто сам вносил одной строкой в декларацию, поэтому суммы видел, а дату недоглядел. Будет исправлено.

**Comment by titov-vv** [comment]
Исправил. Но фикс простой, поэтому я не тестировал. Проверьте, пожалуйста.

**Comment by jetfraer** [comment]
Пардон, как проапдейтиться? upgrade новый package не находит, руками пробовал подсунуть taxes.py - там, видимо, какие-то референсы еще поменялись, слишком сложно для меня :)

**Comment by titov-vv** [comment]
Хм... я так понимаю вы через `pip install` ставили. Тогда лучше через него я думаю и обновиться будет. Постараюсь зарелизиться на днях, т.к. действительно очень много было изменений за последнюю неделю - не стоит смешивать разные способы апдейтов...

**Comment by jetfraer** [comment]
Проверил, дата указывается в декларации теперь расчетная, рублевая сумма также на дату расчетов. Однако курс указан по-прежнему на дату сделки (операция та же, что и на скрине в начале топика).
![image](https://user-images.githubusercontent.com/80484013/111149945-8ce3d300-859e-11eb-9b0a-dff3de321241.png)

Также вижу, что изменился порядок сделок в отчете - раньше по дате покупки, теперь по тикеру. В принципе норм :) 

Однако в новом отчете у меня исчезла одна сделка, как в экселе, так и в декларации! Чем она отличается от других, пока не понял. Скрин из предыдущего отчета:
![image](https://user-images.githubusercontent.com/80484013/111150366-11ceec80-859f-11eb-8e15-90ee03d0430a.png)

**Comment by titov-vv** [comment]
Начну с конца:
- да, сделка исчезла, это результат f1c90d0 и это правильно - по ней расчёты прошли 04.01.2021, поэтому она уже пойдёт в отчет по 2022.
- порядок да, изменил - причина банальна - теперь он совпадает с порядком в отчёте IB.
- м... да, похоже с курсом не доглядел, каюсь. Попробуйте в `reports/taxes.py` поменять в 524-й строке с
`deal['spending_rub'], deal['c_rate'])`
на
`deal['spending_rub'], deal['cs_rate'])`
(букву s добавить в c_rate). Должно помочь. Если будет ок, то я внесу вечером изменения.

**Comment by titov-vv** [comment]
Скорректировал в e8f6773

**Comment by jetfraer** [comment]
>  в reports/taxes.py поменять в 524-й строке
Поменял, теперь всё верно показывает. 
![image](https://user-images.githubusercontent.com/80484013/111466782-c0586600-8734-11eb-86f2-ef65dc2a78a4.png)

Спасибо!!

**Comment by titov-vv** [comment]
Окей. Спасибо что  проверили.
К выходным сделаю новый релиз (ещё пара багов нашлась, ну и может сделаю импорт отчётов ещё одного брокера)
