### ISSUE TITLE
Declaration file - bonds and commissions not included

### ISSUE THREAD

**Issue by jetfraer** [titov-vv/jal#22]
В файле декларации не указываются купонные доходы по облигациям, присутствующие в эксель-расчете.
Также в расходы не включены прочие комиссии.

PS есть какая-то еще площадка для интерактивного общения с автором?

**Comment by titov-vv** [comment]
С купонными доходами - у меня было слишком мало примеров, чтобы надёжно сделать их в декларацию. 
Если пришлёте примеры операций с бондами на jal@gmx.ru то перепроверю всё ещё разок и подумаю как реализовать добавление в файл декларации.
Что касается прочих комиссий, то универсального метода их добавления нет, поэтому тут каждый сам для себя решает каких добавлять и как учитывать. Собственно поэтому они не добавляются, но можно подумать что с этим делать.
Общаться можно по e-mail, есть тема на склянках - https://www.banki.ru/forum/?PAGE_NAME=read&FID=21&TID=379285 есть телеграмм, но там я могу отвечать с большей задержкой.

**Comment by requestinglife** [comment]
У меня есть прочие комиссии в экселе. В частности за использование заёмных средств. Не выгружаются в файл декларации. 
В чём всё-таки проблема их включать в расходную часть, что коды расходов надо ставить разные?

**Comment by titov-vv** [comment]
С комиссиями большой проблемы нет (их просто тут объединили вместе с облигациями, хотя это разные вещи), но нужно понять все ли они должны учитываться (например, за snapshots бывают начисления и возвраты) ну и немного подумать над реализацией уже конкретно у коде, т.к. они должны делаться равномерно между типами активовов (а это значит нужно сначала знать какие именно типы активов входят в декларацию заранее)
