### ISSUE TITLE
MacOS Mojave - нет иконок

### ISSUE THREAD

**Issue by iliakan** [titov-vv/jal#24]
Инсталял при помощи pip install jal.

Запустил, и в обоих языках что-то с иконками (См справа где плюс и минус должен быть):
![image](https://user-images.githubusercontent.com/349336/111979284-efe0e700-8b15-11eb-92b0-3ed2fbbbf094.png)

Вообще, под MacOS Mojave оно должно работать, кто-то проверял, или на мне будут все шишки? :)

```
❯ pip -V
pip 21.0.1 from /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)

❯ python -V
Python 3.8.8
```

**Comment by titov-vv** [comment]
Под MacOS проверяли, в целом работает, но вот именно подобные проблемы с кнопками в интерфейсе иногда всплывали.
Собственно у меня первый вопрос - они у вас нажимаются? (а то были прецеденты, когда их даже нажать на MacOS нельзя). 
Если нажимаются, то думаю дело в шрифтах и размерах, это поправимо. Просто у меня нет под рукой MacOS для регулярных тестов, поэтому такое иногда вслывает. Я попробую на днях раздобыть её и потестировать.
Если хотите шишек и есть желание потестировать, то напишите мне на jal@gmx.ru - я могу вам выслать модифицированные файлы для тестов, чтобы понять с чем всё-таки проблема связана может быть.

**Comment by iliakan** [comment]
Привет,

Да, нажимаются, но что происходит при этом непонятно.

Еще вот радости:
```
❯ jal
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 2123, in shutdown
    h.close()
RuntimeError: Internal C++ object (LogViewer) already deleted.
```

**Comment by titov-vv** [comment]
При нажатии на "+" (самая левая) дожна добавиться строка в таблицу и там можно будет ввести имя и прочее. Вторая слева "..+" аналогичным образом добавляет дочерний элемент в дерево. По середине "-" для удаления элементов.
Кнопки справа - с галочкой и крестиком - для сохранения изменений или их отката.

Вот это _Internal C++ object (LogViewer) already deleted._ странно, если появилось при обычном выходе из программы. Понаблюдаю. Но иногда такое бывает при аварийном завершении.

**Comment by iliakan** [comment]
А вот под Windows (VM):

![image](https://user-images.githubusercontent.com/349336/112007510-c33cc780-8b35-11eb-8415-126cbf30242d.png)

**Comment by titov-vv** [comment]
Да, в общем с шириной кнопок надо будет поработать ;)

**Comment by titov-vv** [comment]
Я совсем чуть-чуть поменял - под Windows стало вроде нормально на 2021.03.4.
Если есть возможность - попробуйте, стало ли лучше на MacOS.
![peers](https://user-images.githubusercontent.com/55182132/112020584-8545a080-8b41-11eb-8f09-23ddf5cc7893.png)

**Comment by iliakan** [comment]
Как обновиться? pip install jal говорит, что все уже стоит.

Репо клонировать?

**Comment by titov-vv** [comment]
Если я правильно понимаю:
`pip install --upgrade jal`

**Comment by iliakan** [comment]
Смотрю.. Если не сложно, глянь https://github.com/titov-vv/jal/issues/25#issuecomment-804161290 ?

**Comment by iliakan** [comment]
Стало так:

![image](https://user-images.githubusercontent.com/349336/112021454-5e3b9e80-8b42-11eb-88c1-af58ae8f8413.png)

Вообще, это приемлемо =)

**Comment by titov-vv** [comment]
Хм... приемлимо-то приемлимо... но что ж их так по высоте то.... хотя.. кажется догадываюсь в чём дело - разные шрифты подцепляются. Думал упростить себе жизнь и сделать просто unicode-символы вместо иконок... А оно вона как ;) Хотя в linux и windows всё ровненько...
Ладно, может как-нибудь нарисую иконки и заменю на них - тогда будет одинакого. Пока закрываю с тем что есть ;) ибо иконок действительно нет - надо их рисовать ;)

**Comment by iliakan** [comment]
Да, спасибо, больше волнуют непонятки с дивидендами, о которых я параллельно написал :/

**Comment by titov-vv** [comment]
Таки приделал иконки. Теперь должно поприличнее выглядеть ;)
