### ISSUE TITLE
Подойдет ли Jal при отсутствии старых отчётов?

### ISSUE THREAD

**Issue by iliakan** [titov-vv/jal#25]
Нужно составить 3-НДФЛ за 2020.

При этом были некоторые продажи ETF, приобретённых в 2015 году.

За старые года (более 5 лет) никакой возможности получить от Interactive Brokers репорт нет. Я их уже 3 недели трясу по-разному, похоже прям совсем никак. Хотя в HTML-формате данные у меня есть (Activity Report).

Полагаю, подобный вопрос возникнет не только у меня, а у любого человека, который захочет использовать Jal, и покупка была более 5 лет назад.

Позволяет ли Jal как-то решить эту ситуацию? Ввести дату и стоимость покупки вручную, например.

**Comment by titov-vv** [comment]
Да, позволяет. Можно добавить "открывающие" трейды руками, это не  сложно, но может быть муторно, если их много (скажем так, если больше 20-30, то проще на коленке быстро набросать импорт из HTML).
В правой нижней части окна нажимаете кнопку New (Новая) и из выпадающего меню выбираете Buy/Sell (Покупка/Продажа). Далее заполняете поля с деталями операции - пример на скриншоте ниже - дата, счет, бумага, количество, цена, комиссия. Желательно таже дату расчётов. Номер и коментарий не обязательны.
Для сохранения нажимаете галочку (хотя опасаюсь её у вас на MacOS тоже не будет видно....)
![buy-sell](https://user-images.githubusercontent.com/55182132/111988060-0c365100-8b21-11eb-943c-01baa7edbc3c.png)

**Comment by iliakan** [comment]
@titov-vv есть странность в отчетах, может я что-то не понимаю.. Могу ли написать в телеграм?

**Comment by iliakan** [comment]
Справа-снизу "Налог, уплаченный в иностранном государстве" - откуда берётся?
![image](https://user-images.githubusercontent.com/349336/112016742-0bf87e80-8b3e-11eb-9dff-9e72195209ac.png)

Дело в том, что по Dividend report там не было Withholding tax, вот:

![image](https://user-images.githubusercontent.com/349336/112017031-4b26cf80-8b3e-11eb-86f5-dd8874fd97b3.png)

Так как Qualified dividends, то налог не брался.

**Comment by iliakan** [comment]
То есть, непонятно, откуда в декларации взялся "Налог, уплаченный в иностранном государстве" в размере 0.04.

**Comment by iliakan** [comment]
В принципе, я здесь все описал, думал в телеге быстрее.

**Comment by titov-vv** [comment]
Налог взялся из отчёта Interactive Brokers. Т.к. вы не налоговый резидент US, то IB удерживает с вас по обычным бумагам 10% налога.
Соответственно в XML, который вы загружали, есть записи по дивидендам и отдельно по удержанному налогу (Witholding Tax). Т.к. между США и Россией есть соглашение об избежании двойного налогообложения (и соответствующая галочка стоит в меню Data->Countries), то этот налог засчитывается в РФ при продаже декларации.
В рублях я вижу у вас не ровно 10% получилось, но тут есть ещё одна проблема - IB немного округляет налоги (поэтому всех прошу тут голосовать - https://interactivebrokers.com/en/general/poll/featuresPoll.php?sid=15422 ) - возможно это причина. Но может ещё какое округление. В любом случае ваш дивиденд в декларации выглядит нормально на мой взгляд.

**Comment by titov-vv** [comment]
А, прочитал внимательнее вопрос - не сразу увидел отсылку к Dividend report.
- во-первых Dividend Report штука сама по себе странная. У меня, например, некоторые дивиденды в него не попадают. Поэтому я вообще не уверен, что стоит использовать его как эталон.
- но, во-вторых, по вашему случаю скорее всего около февраля 2021-го IB делал корректировку. Если вы грузили отчёт только за 2020-й, то эта корректировка в Jal не попала и поэтому налог остался полность. Т.е. чтобы это учесть надо загрузить ещё отчёт за январь-март 2021 -если там была корректировка, то Jal её учтёт.

Но вообще мы немного отклонились от исходной темы. Предлагаю или открыть отдельную issue для обсуждения, или обсудить в почте/телеграмме/на банки.ру.

**Comment by titov-vv** [comment]
Обсуждение дивидендов в #27

**Comment by iliakan** [comment]
По поводу старых отчетов, которые есть в HTML-виде (Annual Activity Report), это можно как-то заимпортить? 

Вижу, есть импорт из HTML - это оно или что-то совсем другое?

**Comment by titov-vv** [comment]
Нет, это другое (это для российских брокеров - импорт сделок из Quik).
Я очень примерно помню как выглядит Annual Activity Report в HTML - если пришлёте на jal@gmx.ru, то гляну что можно сделать.

**Comment by iliakan** [comment]
Ок, отправил.

**Comment by iliakan** [comment]
Я в письме написал про покупки, но видимо и покупки и продажи надо импортировать для корректности.

А вот остальное - даже не знаю...
