### ISSUE TITLE
Запуск под Windows

### ISSUE THREAD

**Issue by iliakan** [titov-vv/jal#26]
Решил попробовать под Windows, которая в виртуалке на моей основной ОС.

Поставил туда python 3.8 x64 и запустил pip install jal.

А как его потом запускать?

Вот попробовал перейти в пакет и запустить python3 jal.py, но как-то оно не работает:

![image](https://user-images.githubusercontent.com/349336/112003126-abfbdb00-8b31-11eb-96ed-7c2c87a90499.png)

**Comment by iliakan** [comment]
Внимательно прочитал readme - нашел в Scripts

**Comment by titov-vv** [comment]
Кстати, я просто кликом на `jal.py` под Windows запускаю, но не помню делал ли что-то специально для этого. Возможно пути прописаны.
