### ISSUE TITLE
Дивиденды

### ISSUE THREAD

**Issue by iliakan** [titov-vv/jal#27]
Справа-снизу "Налог, уплаченный в иностранном государстве" - откуда берётся?

Вот скрин из Декларации 20, один дивиденд:
![image](https://user-images.githubusercontent.com/349336/112016742-0bf87e80-8b3e-11eb-9dff-9e72195209ac.png)

Но дело в том, что по Dividend report там не было Withholding tax, вот кусочек:

![image](https://user-images.githubusercontent.com/349336/112017031-4b26cf80-8b3e-11eb-86f5-dd8874fd97b3.png)

Так как Qualified dividends, то налог не брался.

======
Dividend report скачал только что за 2020, как и отчёт.

Возможно, различие из-за корректировок? Я не очень разобрался с этим.
Как быть с этими корректировками? ;)

**Comment by titov-vv** [comment]
Я на 95% уверен, что налог был скорректирован в феврале 2021. 
Загрузите в *jal* отчёт за январь-март 2021 - если там были корректировки, то налог будет обновлён.
Только загружайте отчёты по одному разу и по порядку - сначала 2020 (я так понимаю это вы уже сделали), потом 2021. Если загрузить несколько раз, то есть риск задвоения некоторых операций.

**Comment by iliakan** [comment]
То есть, правильно ли я понимаю, что, несмотря на то, что налог нужен за 2020 год, мне нужно дополнительно загрузить отчет за текущую часть 2021го, чтобы правильно налоги посчитались?

**Comment by titov-vv** [comment]
В целом да. Эта тема часто всплывает в вопросах, недавно обсуждали и в facebook и ![в теме на банки.ру](https://www.banki.ru/forum/?PAGE_NAME=read&FID=21&TID=379285)
Там есть один нюанс: IB делает эти корректировки до 15 марта следующего года (чаще всего в феврале). Но иногда они датируются предыдующим годом и не вызывают проблем, а иногда следующим, хотя явно видно, что это корректировка за прошлый год. После нескольих обсуждений сошлись на мнении, что лучше это всё учитывать в декларации прошлым годом, т.к. иначе будет занижение налоговой базы. 
С поддержкой IB общались на тему правильности дат, но толи они не понимают, толи действительно не могут. Я создал недавно запрос на изменения в ![Feature Poll](https://interactivebrokers.com/en/general/poll/featuresPoll.php), но он ещё не прошёл модерацию.

**Comment by iliakan** [comment]
Загрузил, пересчитал.

![image](https://user-images.githubusercontent.com/349336/112048414-6e15ab80-8b5f-11eb-8adf-95ee30b11c3f.png)

Теперь верно!

**Comment by iliakan** [comment]
Оставляю открытой, с учётом того что задокументировать "фичу" всё же надо бы.

**Comment by titov-vv** [comment]
Ok. Может найдутся желающие описать :) или у меня руки дойдут

**Comment by iliakan** [comment]
Я опишу, когда закончу декларацию делать.

**Comment by titov-vv** [comment]
Доки обновились
