### ISSUE TITLE
Новый импорт из HTML, вводить ли assets?

### ISSUE THREAD

**Issue by iliakan** [titov-vv/jal#28]
Запустил на чистой базе импорт из activity report за 2015.

Задаёт вопросы такого вида:

![image](https://user-images.githubusercontent.com/349336/112529013-dcec4200-8db5-11eb-915f-73e8aff9217e.png)

Это нормально? 

VHT - это ETF. Выбирать Funds? 

Что-то еще вводить? На что это влияет?

**Comment by iliakan** [comment]
Вот такие assets в итоге получились, все верно? Страна не нужна или еще что-то?

![image](https://user-images.githubusercontent.com/349336/112532140-85e86c00-8db9-11eb-817e-8836c75ce39f.png)

**Comment by iliakan** [comment]
Загружу сначала XML, он создает assets.

**Comment by titov-vv** [comment]
Да, это правильное поведение. 

HTML-импорт ограничен по фукционалу и данные о ценных бумагах не импортирует - поэтому они либо уже должны быть в базе (например, из XML, как вы и сделали), либо их нужно создать в этом диалоговом окне.
В нём:
Symbol - тот тикер под которым бумага торгуется на бирже, указана в отчётах (используется для идентификации бумаги, загрузки котировок и т.п.)
Name - полное наименование бумаги, в общем-то может быть произвольным
Type - тип ценной бумаги: Money - валюты, Shares - акции, Bonds - облигации, Funds - ETF, ПИФ и т.п., Derivatives - ПФИ, Commodities - "сырьё" (ну я для ОМС создал просто). Для Interactive Brokers это влияет на то в какую часть налогового отчёта попадёт бумага (или не попадёт вообще, если это Money или Commodities, например)
ISIN - международный идентификатор бумаги, он есть не для всех, но когда он есть Jal использует его, т.к. это надёжнее чем использовать тикер
Quote source - откуда котировки брать.

Ещё есть Country (страна) - она появилась позже, чем это окошко, поэтому надо будет доделать, кстати. Она важна для учёта СОИДН в налоговом отчёте.

**Comment by iliakan** [comment]
Нормально что "Data Source": None после импорта XML?

Такая картинка ок?

![image](https://user-images.githubusercontent.com/349336/112584841-b35d0600-8e09-11eb-8780-2cd6af55ee4c.png)

**Comment by titov-vv** [comment]
Да, нормально.
Data source при импорте не выставляется (он используется только для загрузки котировок - для налогов это не нужно). Я пока не решил как можно его корректно указать при импорте, чтобы не было лишней путаницы.

ISIN не понмю, должен импортироваться или нет. Но в целом это нормально - во-первых ISIN далеко не всегда есть в отчётах, во-вторых этот кусок кода не очень удачный, я его буду переписывать, там и перепероверю На данный момент это выглядит нормальным.

**Comment by iliakan** [comment]
Спасибо.
