### ISSUE TITLE
Withdrawal - автоматизация

### ISSUE THREAD

**Issue by iliakan** [titov-vv/jal#29]
Делаю импорт XML за 2017 год.

Получаю пачку вопросов такого вида:
![image](https://user-images.githubusercontent.com/349336/112533050-977e4380-8dba-11eb-98ce-222875dd85f0.png)

Это ок? Я перед этим создал Bank accounts:

![image](https://user-images.githubusercontent.com/349336/112533120-ab29aa00-8dba-11eb-9c8f-4b3e2cc7b30d.png)

 Стесняюсь спросить - можно ли, чтобы автоматом нужный банковский счет выбирало, с той же валютой? Для налогов ведь это вообще не важно.

**Comment by iliakan** [comment]
Когда много операций - легко ошибиться, и потом непонятно как поправить.

**Comment by iliakan** [comment]
P.S. Или может сделать один счет в RUB и туда все операции скидывать, во всех валютах? Тогда проблемы ошибиться нет, не знаю какие побочные эффекты =)

**Comment by titov-vv** [comment]
Это нормальное и правильное поведение.

> можно ли, чтобы автоматом нужный банковский счет выбирало, с той же валютой? Для налогов ведь это вообще не важно.

Да, для налогов это не важно. Но... Jal создавался не для налогов (точнее теперь уже - не только для налогов) :)
Я не очень представляю как выбрать автоматом - кроме валюты ничего больше об этом счёте не известно и т.к. Jal может иметь кучу счето в этой валюте, то у меня пока нет идеи как выбрать из них нужный.

> Когда много операций - легко ошибиться (enter лишний раз нажать не на том счёте), и потом непонятно как поправить.

Если все переводы с одного счёта, то тут как раз достаточно нажимать *Enter* - Jal запоминает последний выбранный счёт и предлагает по умолчанию его.
Если счета/валюты разные, то как уже выше написал - пока кроме как вручную не знаю как можно это определить. Но для ручного ввода не обязательно тыкать в *meatballs* (...), в строке ввода работает автодополнение - так что можно начать набирать первые символы названия счета, чтобы выбрать нужный.
Но даже если получилась ошибка, то в общем-то ничего сильно страшного - поправить просто. Для этого достаточно выбрать эту операцию в списке операций, изменить в ней счёт и сохранить.

> Или может сделать один счет в RUB и туда все операции скидывать, во всех валютах? Не знаю какие побочные эффекты =)

Если важны исключительно налоги, то можно сделать и так. Для расчёта налогов эта информация не используется, она нужна в целом для учёта того откуда куда деньги пришли-ушли. Если все трансферы закинуть на один счет в произвольной валюте, то данные на этом счёте будут абсолютно бесмысленны, но на расчёт налогов это не повлияет.

**Comment by iliakan** [comment]
А сложно добавить галочку "don't ask any more" там где счет выбирается? ;) или что-то такое.

**Comment by titov-vv** [comment]
Нет, я думаю вполне реально и точно не сложнее галки не учитывать settlement в расчётах.
Так что сделаю, но чуть позже, как более критичное проверится-поправится.
