### ISSUE TITLE
Ошибка в курсе валют в отчете

### ISSUE THREAD

**Issue by iliakan** [titov-vv/jal#34]
Попробовал запустить процесс с декларацией за 2020 год.

- Сделал Load Quotes с 2010 года по 2021 примерно так:

![image](https://user-images.githubusercontent.com/349336/112713766-dd84f580-8ee7-11eb-8ff3-c888fdb70605.png)

- После Tax Report [RU] в excel появились такие строки:
![image](https://user-images.githubusercontent.com/349336/112713430-00aea580-8ee6-11eb-8349-b3b8c01576a7.png)

Тут курс доллара 35, определенно он таким не был 2020м году. 

Неверный курс на всех страницах Excel-отчета.

**Comment by titov-vv** [comment]
Интересно... Так глубоко я курсы не загружал. Проверю - есть сильное подозрение, что сервер не готов кому-попало отдать такой длинный интевал и он отдаёт ограниченный объём, года за 3 максимум, например.
Как результат - курсы грузятся успешно, но не все, например. А ошибок не возникает, т.к. сервер всё-равно отдаёт данные.
Пока это теория, надо проверить. Самый простой способ - заглянуть в Data->Quotes (там можно фильтр по символу) - будет видно для каких дат котировки есть.
Если подтвердится, то как временное решение - подгрузить недостающие аналогичным образом, но с другими датами.

**Comment by iliakan** [comment]
В data/quotes все ок по виду.

**Comment by iliakan** [comment]
Прислать базу?

**Comment by titov-vv** [comment]
Да, можно. Если в котировках все видны даты до 2020-го года... то да, это что-то интересное, лучше напрямую в базе глянуть.

**Comment by titov-vv** [comment]
Сделал такую-же длинную загрузку у себя - курсы успешно загрузились с ЦБ.
Пропробовал на своих отчётах - проблема не воспроизводится, в таблице правильные курсы за 2020-й.
Что-то явно не так, но что, пока непонятно что именно. 
Если пришлёшь базу, то это поможет разобраться. Можно удалить все операции, кроме проблемных дивидендов, например (мышкой выделить в главном окне и по правой кнопке - удалить)

**Comment by titov-vv** [comment]
Закрываю, т.к. пока больше не удалось ни разу воспроизвести.
