### ISSUE TITLE
Декларация за 2 счета в IB

### ISSUE THREAD

**Issue by iliakan** [titov-vv/jal#41]
Как действовать, если в IB открыто 2 accounts у одного человека?

Верно ли так?

1. Создать дополнительные счета Data → Accounts и импортировать все отчёты (они подхватятся как надо?).
2. Вызвать Reports → Tax Report два раза, указав при втором вызове .dc0-декларацию, заполненную в результате первого вызова (добавит записи?).

**Comment by titov-vv** [comment]
По п.1 ответ - да. Т.к. номера у account'ов разные, то нужно создать отдельные счета - они будут отличаться номером счета в столбце `Account #`

По п.2 в целом тоже ответ да, так должно работать - jal не удаляет предыдущие данные из декларации, а только добавляет новые. Но я не успел протестировать такой вариант и с двумя счетами ещё больше рисков, что не влезут все операции. В общем так сделать можно, но я бы рекомендовал светить получившиеся в декларации итоги более внимательно.
