### ISSUE TITLE
Операции с валютами

### ISSUE THREAD

**Issue by requestinglife** [titov-vv/jal#42]
Насколько я правильно понял, налоговую интересуют также операции по покупке\продаже валюты в валютной секции IB.

Например, заводил я на счёт рубли, потом менял на доллары. На доллары покупал акции. Затем менял доллары на рубли обратно.

Не нашёл в сделках такой информации, хотя брокер мне делает отчёт по движению валютной секции. 
Также не нашёл в выгрузке в эксель и для налоговой секцию операций с валютами? Или это как-то по другому решается?

**Comment by titov-vv** [comment]
С валютой всё весьма неоднозначно. Начиная с того, считать её имуществом или нет. 
Однозначной позиции по этому вопросу нет. Налоговая тоже пока явно свою позицию не обозначила.
Поэтому операции по обмену валюты в налоговый отчёт никак не попадают.

**Comment by titov-vv** [comment]
В facebook было [довольно интересное обсуждение](https://www.facebook.com/groups/ibrus/permalink/1256272884766813)  не так давно на эту тему. Там приведено много разных аргументов, но всё опять сводится к тому является валюта имуществом или нет... В этом отношении я пока принимаю мнение, высказанное там Татьяной Сафоновой:

> В гл 23 НК РФ нет нормы требующей обложения налогом прироста стоимости валюты. К тому же обмен валюты не признается реализацией, а безналичная валюта не признается имуществом (часть 1 НК РФ), соответственно общие нормы гл 23 к валюте также не применяются.

Пока весы этих обсуждений наша налоговая не качнула ни в какую сторону. Поэтому я принимаю эту точку зрения и не планирую обсчитывать валюту для налогов.
Если же кто-то целенаправленно торгует на Форексе и хочет считать налоги через JAL, то дайте знать конкретный кейс - это потребует отдельного обдумывания, т.к. сейчас каждый счет имеет только одну свою валюту и обмен валюты осуществляется переводом между разными счетами... Если форексный счет будет сам по себе, то вероятно это не очень сложно сделать... но вот если мешать форекс с акциями, то могут быть сложности. Поэтому пока для IB без особой нужды реализовывать это не планирую.
