### ISSUE TITLE
Название эмитента при экспорте в программу Декларация

### ISSUE THREAD

**Issue by requestinglife** [titov-vv/jal#43]
При экспорте в программу Декларация у дивидендов отображается название эмитента, а у акций почему-то нет, там только название счёта.
Можно сделать чтобы тоже отображалось?

![image](https://user-images.githubusercontent.com/82116834/116478189-250bf200-a897-11eb-8355-75fbec6f7f89.png)

**Comment by titov-vv** [comment]
Указывается не название счёта, а название банка/брокера, которое вы указали при создании счёта.
Для дохода при продаже ценных бумаг указывать название эмитента некорректно, т.к. он к этой операции отношения не имеет.
Есть мнение, что и для выплат дивидендов нужно указывать наименование брокера, а не эмитента. На банки.ру была как-то дискуссия по этому поводу - в целом аргументы обеих сторон выглядят для меня одинакого убедительными и разумными. Поэтому вероятно к следующему сезону сделаю галочку, чтобы для дивидендов можно было выбирать что указывать.

**Comment by requestinglife** [comment]
Может и не имеет, но когда у тебя сотни анонимных записей и листов в декларации, работать с ними просто неудобно. А чем они плохи? При составлении нам и инспектору при проверке будет полезно. Предлагаю если уже делать галочку то распространить её действие для акций тоже:)

**Comment by titov-vv** [comment]
Это не про удобство, это немного про другое... Поле называется "Источник выплаты". 
Для дивидендов есть некоторая неоднозначность со ст.232 НК РФ - а именно о том, какие документы должны быть предоставлены и от кого, чтобы подтвердить уплату налога по СоИДН. В связи с этим есть мнение, что для дивидендов лучше указывать источником выплаты брокера, а не эмитента.
Но для сделок - эмитент вообще не в курсе, что вы делали с его акциями. Поэтому указывать его в поле "источник выплаты" совсем нелогично. 
С точки зрения удобства - такова уж форма 3-НФДЛ, в ней много странностей и неудобностей...

**Comment by requestinglife** [comment]
Я у себя сделал промежуточный вариант, написал источник и далее наименование эмитента, считаю это никак не нарушит  НК РФ, просто уточнение источника, я просто рядом написал, но можно в скобках его написать.

![image](https://user-images.githubusercontent.com/82116834/118480885-450f3280-b72c-11eb-96ed-386bea448fa2.png)

**Comment by titov-vv** [comment]
Окей, приму к сведению.
Пока чётких планов нет, поэтому обещать тоже не буду. Вы пока единственный, кто попросил такое и у меня пока сомнения с НК РФ, Закрывать не буду - пусть висит, возможно кто-то ещё выскажет мнение за/против и это поможет определиться.
