### ISSUE TITLE
No selection when importing IBKR flex report

### ISSUE THREAD

**Issue by vikmary** [titov-vv/jal#51]
When I import an IBKR report, a new account is being created automatically. But when i choose as the selected one and click `OK`, it shows an error saying "No selection: Please select different account". Am i selecting wrong (i do triple click on the wanted account)?
![image](https://user-images.githubusercontent.com/17520043/147443465-80faa871-b803-4ba0-84e9-098c91c1d688.png)

**Comment by vikmary** [comment]
Sorry, I figured out what was wrong. I had to choose bank account, not investment account. Thank you

**Comment by titov-vv** [comment]
Yep, you got it right.
The question was about deposit - you should use another account to indicate where money came from.
