### ISSUE TITLE
Ошибка по корпоративным действиям (split initial amount failure)

### ISSUE THREAD

**Issue by jetfraer** [titov-vv/jal#53]
Traceback (most recent call last):
  File "c:\users\aleontye\appdata\local\programs\python\python38\lib\site-packages\jal\widgets\main_window.py", line 241, in onStatementImport
    self.ledger.rebuild()
  File "c:\users\aleontye\appdata\local\programs\python\python38\lib\site-packages\jal\db\ledger.py", line 446, in rebuild
    operationProcess[self.current['type']]()
  File "c:\users\aleontye\appdata\local\programs\python\python38\lib\site-packages\jal\db\ledger.py", line 340, in processCorporateAction
    raise ValueError(self.tr("Unhandled case: Corporate action covers not full open position"))
ValueError: Unhandled case: Corporate action covers not full open position

Где-то давится corporate actions. в отчете: 
![image](https://user-images.githubusercontent.com/80484013/151240363-3115fd8f-43a0-410d-bef7-87f6e0456a8c.png)

А в экспорте только
![image](https://user-images.githubusercontent.com/80484013/151240530-bbd4b886-d403-4360-8be4-87d0b72d8218.png)

**Comment by titov-vv** [comment]
Данная ошибка происходит, когда почему-то нет достаточного количества ЦБ на дату корпоративного события.
Судя по отчёту это происходит для сплита HYLB, который случился 13 апреля. 
А вот со сплитом что-то не совсем понятное мне. Например, берём следующий сплит - по VXX от 22 апреля. По нему видно из отчёта, что 25 "старых" акций списали и 6.25 "новых" зачислили - как раз в соотношении 4:1. А вот по HYLB - я вижу как зачислилось 54.25 "новых" акций, но совсем непонятно сколько должно было списаться старых. Если взять коэффициент 4:5 из описания, то получается "старых" должно было быть 43.4 штуки. Т.к. получилось дробное число, то я сильно подозреваю, что упускаю какую-то деталь тут.
В общем я бы проверил всю историю операций с этой бумагой (HYLB) - когда сколько куплено, сколько реально бумаг было перед сплитом (тут можно посмотреть через отчёт Holdings на 12 апреля, например), посмотреть на сайте компании правила спплита и понять как и сколько должно было зачислиться, чтобы это всё сверить в первую очередь...
Но пока больше всего есть ощущение, что в отчёте IB по какой-то причине отсутствует вторая строка для этого сплита, что выглядит очень странным. Кстати, импорт XML прошёл без ошибок? Там не было каких-то сообщений про не найденные парные записи? (Если не было, то хотелось бы ещё взглянуть на XML для этого сплита, т.к. тогда получается там были обе записи...)

**Comment by titov-vv** [comment]
Детали можно в почти продолжить, если удобнее.

**Comment by jetfraer** [comment]
Добрый день!

 

До сплита было 217 HYLB (куплено всё в 2020), после сплита стало 271,25 – как раз 4:5. 54,25 – бумаг добавилось. Отображение в отчете действительно странное. 

Можно что-то сделать, чтобы проигнорировать эту ситуацию, или исправить ее вручную? 

 

При импорте точно не помню, кажется, была ошибка о непарности. 

Как можно очистить полностью базу, чтобы загрузить туда отчеты начисто и проверить еще раз?

 

Вот детали из отчета:

 





 

Сделки (продал всю позицию)



 

 

 



 

 

 



 

BR

Anton

**Comment by titov-vv** [comment]
Похоже вы ответили через письмо и GitHub не подцепил картинки из него. По крайней мере я их не вижу.

> До сплита было 217 HYLB (куплено всё в 2020), после сплита стало 271,25 – как раз 4:5. 54,25 – бумаг добавилось. Отображение в отчете действительно странное.

Да, точно, теперь я вспомнил. В прошлом году действительно был только один такой кейс и похоже я где-то в нём с математикой напутал. Перепроверю и исправлю.

> Можно что-то сделать, чтобы проигнорировать эту ситуацию, или исправить ее вручную?

Думаю можно. Судя по всем проблема только в количестве. Нужно найти эту операцию в списке (выберите счёт, интервал дат и выделите нужный сплит). Скорее всего в нём будут неверные количества бумаги до и после - укажите правильные цифры и нажмите зелёную галочку (тоже самое для JJN надо). После того, как обе исправите, лучше сделать `Data->Re-build Ledger, Full`

> Как можно очистить полностью базу, чтобы загрузить туда отчеты начисто и проверить еще раз?
Самый быстрый и простой способ - удалить файл `jal.sqlite`

**Comment by titov-vv** [comment]
Если хотите - напишите мне на почту jal@gmx.ru - я могу выслать вам подправленный файл `ibkr.py`. После его замены должно посчитаться правильно (по крайней мере на бумажке у меня сейчас цифры сошлись. JJN я так понял у вас 8 шт было.)

**Comment by titov-vv** [comment]
Файл в почту выслал вчера (тут пишу на всякий случай, если вдруг что-то не долетело по адресу)
