### ISSUE TITLE
Menu "Data-Backup..." error

### ISSUE THREAD

**Issue by UmkaBearpaw** [titov-vv/jal#56]
After choose file for backup got this error:
![image](https://user-images.githubusercontent.com/16036509/152688976-ee14f9b3-9821-4fc8-af1b-0a52cbc7f568.png)

In console same error:
![image](https://user-images.githubusercontent.com/16036509/152689046-c0fdb1f4-a7dc-4b23-9f00-f88875c8b4f6.png)

**Comment by titov-vv** [comment]
Windows specific. Seems to be caused by shared file access problem.

**Comment by titov-vv** [comment]
Seems to be a Python bug https://bugs.python.org/issue22107
