### ISSUE TITLE
Не все котировки загружаются

### ISSUE THREAD

**Issue by dimjava** [titov-vv/jal#61]
Название инструмента может различаться в IB и yahoo.finance. 
Например TSL (IB) vs TSL.L (yahoo). Или по разному указываются привилегированные акции (PBR A vs PBR.A vs PBR-A).

Можно попробовать упростить разрешение таких случаев, добавив в интерфейс возможность указать тикер на yahoo, который соответствует тикеру в IB. Либо попробовать сделать поиск через ISIN.

**Comment by dimjava** [comment]
Вот тут пример есть

https://money.stackexchange.com/questions/141162/how-to-query-a-stock-with-the-yahoo-finance-api-by-isin

**Comment by titov-vv** [comment]
За ссылку спасибо, как раз хотел спросить. Почитаю.
Но не факт, что другие сервисы смогут по ISIN отдавать... (вообще я немного удивляюсь, что по ISIN легко искать российские бумаги, а вот зарубежные не так просто...)
Поэтому мне кажется, что идея с альтернативным тикером вполне здравая

**Comment by dimjava** [comment]
Yahoo вроде резво отдает всё в поиске по isin, но в апи только по тикеру. 

Можно сделать именно для Yahoo_Downloader сначала обращение к апи по тикеру, а если не нашел, то пробует сходить в поиск и там первый результат в выдаче.

 Понятно, что все равно наверное ошибки будут, но еще меньше

**Comment by titov-vv** [comment]
Прикручу. Но чуть позже - когда новую структуру базы данных закомичу в master.

**Comment by titov-vv** [comment]
Я посмотрел повнимательнее, оказалось что это акция с LSE - это объясняет наличие суффикса L. 
Пока я сделал это как отдельный источник данных (на самом деле тот же Yahoo), т.к. там котировки отдаются в GBP. 
В будущем вероятно сделаю ещё проверку валюты. 
В целом если этого будет недостаточно, то да, теперь можно будет добавить отдельные тикеты для разных бирж.
