### ISSUE TITLE
Corporate action type is not supported

### ISSUE THREAD

**Issue by ivazin** [titov-vv/jal#63]
Здравствуйте! Столкнулся с ошибкой:
```
2022-04-03 03:24:35,279 - WARNING - Корпоративное действие не поддерживается: RI
2022-04-03 03:24:35,281 - ERROR - Ошибка импорта: Corporate action type is not supported: {'type': -1, 'account': 4, 'asset': 76, 'asset_type': 'stock', 'timestamp': 1628713500, 'number': '17351722443', 'description': '698(KYG8917X1218) SUBSCRIBABLE RIGHTS ISSUE  1 FOR 2 (2965, TONGDA GROUP HOLDINGS LTD - RIGHTS, KYG8917X1RTS)', 'quantity': 25000.0, 'value': 0.0, 'proceeds': 0.0, 'code': '', 'jal_processed': False}
```
Не подскажете, есть ли какой вариант, что с этим можно сделать? )

Ri — Reimbursement, судя по IB reporting guide

В русскоязычном отчете нашлось такое:
```
HKD
2021-08-12 | 2021-08-11, 20:25:00 | 698(KYG8917X1218) Выдача прав по подписке 1 за 2 (2965, TONGDA GROUP HOLDINGS LTD - RIGHTS, KYG8917X1RTS) | 25,000 | 0.00 | 0.00 | 0.00 |  
2021-09-17 | 2021-09-15, 20:25:00 | (KYG8917X1390) Исключены из листинга (2965, TONGDA GROUP HOLDINGS LTD - RIGHTS, KYG8917X1390) | -25,000 | 0.00 | 0.00 | 0.00

```

**Comment by titov-vv** [comment]
Я первый раз сталкиваюсь с таким корпоративным действием, поэтому в JAL оно никак не обрабатывается.
Чтобы добавить его поддержку нужно больше информации:
1) нужно пример из XML - по хорошему не только запись CorporateAction, но желательно ещё SecurityInfo и прочее сопутствующее если есть.
2) нужно описание, что это вообще такое произошло. Я пока бегло нашел только какую-то информацию на немецком на сайте Xetra, что мне не очень помогло понять что это и как должно обрабатываться и какие налоги повлечет.

Плюс у вас там второе ещё действие - "Исключены из листинга". Его недавно добавлял, по идее должно поддерживаться.

**Comment by ivazin** [comment]
Пересмотрел отчет, вроде как это просто право на что-то выдавалось, которым я не воспользовался.

Нашел еще в посте у Евгений Когана в августе: 

> Компания Tongda Group (698 HK) провела эмиссию новых акций. Действующим акционерам предлагается сохранить свою долю в компании, докупив по одной новой акции на две имеющиеся. Для этого нужно приобрести права на подписку, которые идут под тикером 2965 HK.
> О допэмиссии Tongda было объявлено в июле, сразу после этого котировки компании резко снизились. Когда мы покупали акции Tongda в августе, предстоящий выпуск новых акций был уже заложен в котировки компании. 

Сами акции 698 HK просто покупались и продавались мной, сделок с 2965 не было.

По идее, это корпоративное действием можно просто игнорировать в подсчете налогов.

Насчет XML — могу отправить, куда подскажете, но желательно не публично бы ) Если что, я с таким же логином в телеграме

**Comment by titov-vv** [comment]
На главной странице адрес указан - [jal@gmx.ru](mailto:jal@gmx.ru) - можете на него выслать. 
Если телеграмм удобнее -там же есть ссылка на группу, маякните там, через личное сообщение можно.
Я сейчас вспоминаю, что мы с Алексеем в начале этого гдоа про Dividend Rights Issue обсуждали - вероятно это тоже самое или очень похожее. Мы тогда сошлись во мнении, что да, их можно игнорировать, т.к. реальные действия потом в других событиях видны. Но у него не было примера XML, т.к. он с CSV работает.

**Comment by titov-vv** [comment]
Я посмотрел ваше общение с Димой. Там тоже CSV, но в целом я кажется понял и думаю сделаю эту доработку.
Но меня смутила одна вещь, поэтому хотел бы уточнить в целом по порядку действий:
- вы сначала купили 698 Tongda KYG8917X1218.
- далее появляется право на покупку 2965 _KYG8917X1RTS_.
- но потом я вижу делистинг 2965 _KYG8917X1390_.
- исходные акции 698 Tongda KYG8917X1218 у вас или остались или в продали их позже.

Проигнорирвать корпоративное событие RI из отчёта - не проблема. Но, тогда возникает вопрос, что мы будем делистить следующим действием... Ну т.е. если я сейчас добавлю код игнорирования RI, то jal сломается при расчёте делистинга. Для этого тоже можно костыль сделать, но... когда количество костылей начинает увеличиваться, я начинаю подозревать, что иду по пути Птолеменя с его эпициклами... (Остапа понесло...). В общем всё-таки хотелось бы на XML посмотреть, чтобы сопоставить SecurityInfo с CorporateActions - может там есть какие подсказки...

**Comment by titov-vv** [comment]
Кстати, вижу вы там про Vesting с Димой общались - вероятно тоже потребуется доработка, не помню, чтобы мне попадались эти случаи в отчётах IB.

**Comment by titov-vv** [comment]
[14cd3fb](https://github.com/titov-vv/jal/commit/14cd3fb9c62f742dc1db4f834b83854c8015219d)

**Comment by titov-vv** [comment]
#14cd3fb

**Comment by titov-vv** [comment]
Fixed in [14cd3fb](https://github.com/titov-vv/jal/commit/14cd3fb9c62f742dc1db4f834b83854c8015219d)

**Comment by titov-vv** [comment]
Vesting и Rights Issue добавил. Войдут в release 2022.4.1
