### ISSUE TITLE
Учет дополнительных комиссий бирж (e.g. LSE)

### ISSUE THREAD

**Issue by Foat** [titov-vv/jal#64]
Пример (укороченная версия)

```xml
<Trade accountId="ID" acctAlias="" exchange="LSE" quantity="10000" tradePrice="0.1296" tradeMoney="1296" proceeds="-1296" taxes="-6.48" ibCommission="-1.17" ibCommissionCurrency="GBP" />
```

См поле `taxes`, это идет как комиссия LSE за покупку активов (0.5%). Скорее всего это нужно учитывать как комиссию, в том числе в налогах.

На данный момент учитывается только поле `ibCommission`

**Comment by titov-vv** [comment]
Спасибо, вроде всё хорошо в коде, сделаю merge. 
Меня только в этом всём всегда смущало поле `ibCommissionCurrency`. Я пока не делал поддержку отдельных валют.
А вот с `taxes` - оно всегда в валюте сделки идёт? Не было других вариантов?

**Comment by Foat** [comment]
Проверил, задвоение происходит в программе, при экспорте не нашел где это указывается.

**Comment by titov-vv** [comment]
Я заметил, то в PR подправили. Может был и просто автоматический merge с моими изменениями, но может у нас возникло какое-то недопонимание.
Т.к. в итоге вы подтвердили, что происходит задвоение, то я думаю пока оставить код как есть, не включая ваш PR. 
В будущем я попробую сделать привязку комиссий и прочего к бумаге, но тут надо подумать как это лучше реализовать.

**Comment by Foat** [comment]
Да, там просто обновил ветку, чтобы сгенерировать отчет для налоговой. Привязку сделать сложнее гораздо, посмотрел код.

PR да, issue мб оставить для конечного фикса? Тут как удобнее.

**Comment by titov-vv** [comment]
Да, пусть наверное issue будет, чтобы эта идея как-то была озвучена. Может летом после ОоДДС сделаю.

**Comment by titov-vv** [comment]
Те, что с явным указанием номера сделки (как в этом примере для stamp tax для LSE) включил в комиссии за сделки, будет в 2024.2.2.
Те, что без указания на сделки (как за ADR) возможно потом добавлю, но там надо подумать будет как лучше сделать.
