### ISSUE TITLE
Ошибка на операциях замены акций

### ISSUE THREAD

**Issue by ziriy** [titov-vv/jal#73]
Программа не может обработать операции замены и сплита акций. 
Пояснения:
1. Исходная акция была заменена на другу в силу реорганизации компании.
2. Исходная акция была разделена на две других в силу выделения из компании активов.

**Comment by titov-vv** [comment]
А можно чуть подробнее, что именно происходит? Какие ошибки?

**Comment by titov-vv** [comment]
Т.к. вы не описали, что именно происходит, то могу лишь догадываться. 
Подозреваю, что вы получили сообщение об ошибке, описанное под первым номером в [этом разделе](https://github.com/titov-vv/jal/blob/master/docs/error_description.ru.md)
В связи с этим закрываю. Если я не прав и что-то более серьёзное, то напишите детали, пожалуйста.
