### ISSUE TITLE
Дивиденды при короткой позиции

### ISSUE THREAD

**Issue by v0id24** [titov-vv/jal#82]
На вкладке Дивиденды эти события отображаются, в колонке Доход - отрицательный.

Но они сейчас не экспортируются в .dcx
Их можно экспортировать как убытки:

Полученный доход:
- код дохода 1530
- В иностранной валюте 0

Вычеты:
- код вычета 201
- Сумма вычета (расхода) в рублях <сумма>

**Comment by titov-vv** [comment]
Ок, об этом как-то не подумал. Доделаю.

**Comment by titov-vv** [comment]
@v0id24 , вопрос возник небольшой - правильно я понимаю, что у вас эти события в отчёте IB идут не как DIVIDEND, а как PAYMENT IN LIEU OF DIVIDEND?

**Comment by titov-vv** [comment]
На самом деле оно было сделано... но... были перепутаны знаки больше/меньше и код не работал. 
Я подправил, заодно сделал тоже самое для деривативов, чтобы для CFD работало.
