### ISSUE TITLE
Операции купли-продажи бумаг, которые попали на сплит

### ISSUE THREAD

**Issue by v0id24** [titov-vv/jal#83]
Теряются операции купли-продажи бумаг, которые попали на сплит (купили до, продали - после).

Причём, на вкладке "Корп.события" такие Сделки по бумагам отображаются верно.
Но не выгружаются в .dcx

**Comment by titov-vv** [comment]
Это так и должно быть.
Продажи бумаг после корпоративных событий попадают на отдельный лист "Корп.события" - во-первых чтобы было удобнее проверить что с ними всё хорошо, во-вторых по ним расчёты более сложные могут быть.
Собственно по этой причине они и в декларацию не выгужаются - т.к. там могут быть нюансы и лучше это руками проверить. Возможно в будущих версиях это изменится, но пока так.

**Comment by v0id24** [comment]
если можно, где-то комментарий в xls добавить это - было бы здорово
