### ISSUE TITLE
Округление комиссий

### ISSUE THREAD

**Issue by v0id24** [titov-vv/jal#84]
Комиссии в (USD) перед переводом в рубли (местную валюту) обычно округляется

1,084353392 * 57,3917 = 62.23
1,08 * 57,3917 = 61.98

Может набегать небольшая разница итого

**Comment by titov-vv** [comment]
Да, это последствия оптимизации кода. 
На налоги это практически не влияет, т.к. происходит на самом последнем этапе. Возможно исправлю, но ещё не решил - может проще в таблице тоже отображать 1,08 вместо 1,084353392.

**Comment by titov-vv** [comment]
Пока решил что менять не буду, т.к. это ухудшит точность расчётов.
Может быть в будущем сделаю какую-то доработку.
